### ISSUE TITLE
is it compatible with bootstrap ?

### ISSUE THREAD

**Issue by qantuum** [codyhouse/auto-hiding-navigation#4]
Dear team,

thanks for bringing up this tool !
I come to ask whether it is compatible with bootstrap or not ? Indeed, I try to manage the proposed class system as follows : 

```
<header class="cd-auto-hide-header">
  <nav id="global-nav" class="navbar navbar-expand navbar-light fixed-top bg-light d-none d-sm-block">
    <!-- the container-fluid allows to work with flex -->
    <div class="container-fluid">
    	<a class="nav-brand float-left" href="dashboard.php"><img width="150px" src="./img/logo.png" alt="logo"/></a>
    	<ul class="navbar-nav mx-auto flex-nowrap flex-row">
          <li class="nav-item">
            <a class="nav-link" href="#">Nav item</a>
          </li>
        </ul>
    </div>
   <nav>
</header>
<main class="cd-main-content">
---content of page
</main>
```

With adding the js file and the css styles from the tutorial https://codyhouse.co/gem/auto-hiding-navigation;

but it does not work; as a result I just get my nav permanently hidden.

thanks...

**Comment by sebastiano-guerriero** [comment]
Hi there! I'm afraid we can't help with code/bootstrap integration but only look into issues of the component.
